
------------------------------------------------------
-- 카페 테이블 3개 만들기 예제
CREATE TABLE MEMBER(
    ID              NUMBER (20)     NOT NULL PRIMARY KEY,   -- 회원ID
    NAME            VARCHAR2 (20)   NOT NULL,               -- 이름
    REGNO           CHAR (8)        NOT NULL,               -- 생년월일
    HP              VARCHAR2 (13)   NOT NULL,               -- 핸드폰번호
    ADDRESS         VARCHAR2 (100)  NOT NULL                -- 주소
);

DESC MEMBER;

SELECT * FROM MEMBER;
----------------------------------------------------
CREATE TABLE BOOK(
    CODE            NUMBER (4)      NOT NULL PRIMARY KEY,   -- 제품코드
    TITLE           VARCHAR2 (100)  NOT NULL,               -- 도서명
    COUNT           NUMBER (6)      NOT NULL,               -- 수량
    PRICE           NUMBER (10)     NOT NULL,               -- 정가
    PUBLISH         VARCHAR2 (50)   NOT NULL                -- 출판사
);

DESC BOOK;

SELECT * FROM BOOK;
----------------------------------------------------
CREATE TABLE BOOK_ORDER(
    NO              VARCHAR2 (10)   NOT NULL PRIMARY KEY,   -- 주문번호
    ID              VARCHAR2 (20)   NOT NULL,               -- 회원ID
    CODE            NUMBER (4)      NOT NULL,               -- 제품코드
    COUNT           NUMBER (6)      NOT NULL,               -- 주문권수
    OR_DATE         DATE ()         NOT NULL                -- 주문일자
);

DESC BOOK_ORDER;

SELECT * FROM BOOK_ORDER;
--------------------------------------------------

DROP TABLE EMP01 PURGE; -- 복원 필요없이 삭제

CREATE TABLE EMP01 (
    EMPNO NUMBER (4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2 (9),
    DEPTNO NUMBER (4)
);

INSERT INTO EMP01
VALUES (NULL, NULL, 'SALESMAN', 30);

SELECT * FROM EMP01;

CREATE TABLE EMP02 (
    EMPNO NUMBER(4) UNIQUE,--NULL까지 제한하려면 EMPNO NUMBER(4) NOT NULL UNIQUE
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(4)
);

INSERT INTO EMP02(EMPNO, ENAME, JOB, DEPTNO)
VALUES (7499, 'ALLEN', 'SALESMAN', 30);

INSERT INTO EMP02(EMPNO, ENAME, JOB, DEPTNO)
VALUES (NULL, 'JONES', 'MANAGER', 20); 
--NULL은 값(VALUE)에서 제외되므로 유일한 조건인지를 체크하는 값에서 제외된다. 정상실행
INSERT INTO EMP02(EMPNO, ENAME, JOB, DEPTNO)
VALUES (NULL, 'JONES', 'SALESMAN', 10);

SELECT TABLE_NAME FROM USER_TABLES
ORDER BY TABLE_NAME DESC;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP02';

SELECT OWNER, CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = 'EMP02';

DROP TABLE EMP03;

CREATE TABLE EMP03 (
    EMPNO NUMBER (4)    PRIMARY KEY,--primary key는 무조건 not null이며 테이블 당 1개만 존재.
    ENAME VARCHAR2(10)  NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER (4)
);

INSERT INTO EMP03
VALUES (7499, 'ALLEN', 'SALESMAN', 30);

INSERT INTO EMP03
VALUES (NULL, 'JONES', 'MANAGER', 20);

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP03';

CREATE TABLE DEPT01 (
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14) NOT NULL,
    LOC VARCHAR2 (13)
);

Insert into DEPT01 (DEPTNO, DNAME, LOC) values (10, 'ACCOUNTING', 'NEW YORK');
Insert into DEPT01 (DEPTNO, DNAME, LOC) values (20, 'RESEARCH', 'DALLAS');
Insert into DEPT01 (DEPTNO, DNAME, LOC) values (30, 'SALES', 'CHICAGO');
Insert into DEPT01 (DEPTNO, DNAME, LOC) values (40, 'OPERATIONS', 'BOSTON');

SELECT * FROM DEPT01;

INSERT INTO EMP03
VALUES (7566, 'JONES', 'MANAGER', 50);

SELECT * FROM EMP03;

--사원테이블(참조하는 자식테이블)
CREATE TABLE EMP04 (
    EMPNO NUMBER (4) PRIMARY KEY,                   --사원번호
    ENAME VARCHAR2 (10) NOT NULL,                   --사원명
    JOB VARCHAR2 (9),                               --직무
    DEPTNO NUMBER (2) REFERENCES DEPT01(DEPTNO)     --부서번호
);

INSERT INTO EMP04
VALUES (7499, 'ALLEN', 'SALESMAN', 30);

--ORA-02291: 무결성 제약조건(HR.SYS_C008391)이 위배되었습니다- 부모 키가 없습니다
INSERT INTO EMP04
VALUES (7566, 'JONES', 'MANAGER', 50);

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP04';

CREATE TABLE EMP05 (
    EMPNO NUMBER (4) PRIMARY KEY,
    ENAME VARCHAR2 (10) NOT NULL,
    GENDER VARCHAR2 (1) CHECK (GENDER IN('M', 'F')),
    REGDATE DATE DEFAULT SYSDATE
);

--* NOT NULL, CHECK, DEFAULT 변경은
-- ALTER TABLE 테이블 MODIFY(컬럼명 자료형 제약조건)으로

INSERT INTO EMP05 (EMPNO, ENAME, GENDER)
VALUES (7566, 'JONES', 'M');

INSERT INTO EMP05
VALUES (7566, 'JONES', 'M', SYSDATE);

SELECT * FROM EMP05;

INSERT INTO EMP05 (EMPNO, ENAME, GENDER)
VALUES (7566, 'JONES', 'A');

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP05';